<?php
    include("connection.php");
    $id = $_GET['id'];
    $sql = "SELECT * FROM rendelesek WHERE id = '$id'";
    $result = $conn->prepare($sql);
    $result->execute();
    $row = $result->fetch(PDO::FETCH_ASSOC);
    echo "Pizzanév: ";
    echo "{$row['pizzanev']}";
    echo "<br><br>";
    echo "Feltét: ";
    echo $row['feltetnev'];
    echo "<br><br>";
    echo "Méret: ";
    echo $row['meret'];
    echo "<br><br>";
    echo "Mennyiség: ";
    echo $row['mennyiseg'];
    echo "<br><br>";
    echo "Ár: ";
    echo $row['ar'];
    echo "<br><br>";
    echo "Rendelés ideje: ";
    echo $row['rendeles_ideje'];
    echo "<br><br>";
    echo "Szállítási cím: ";
    echo $row['szallitasi_cim'];
    echo "<br><br>";
    echo "Telefonszám: ";
    echo $row['telefonszam'];
    echo "<br><br>";
    echo "<form action='index_elado.php' method='post'>";
    echo "Kézbesítés: ";
    echo "<input type='hidden' name='hidden_id' value='{$row['id']}'>";
    echo "<select name='kezbesites'>";
        echo "<option value='{$row['kezbesites_statusz']}'>{$row['kezbesites_statusz']}</option>";
        echo "<option value='nem ismertt'>nem ismert</option>";
        echo "<option value='sikeres'>sikeres</option>";
        echo "<option value='sikertelen'>sikertelen</option>";
    echo "</select>";
    echo "<br><br>";
    echo "Kiszállítás ideje: ";
    echo $row['kiszallitas_ideje'];
    echo "<br><br>";
    echo "Rendelés státusz: ";
    echo "<select name='rendeles'>";
        echo "<option value='{$row['rendeles_statusz']}'>{$row['rendeles_statusz']}</option>";
        echo "<option value='beérkezett'>beérkezett</option>";
        echo "<option value='készül'>készül</option>";
        echo "<option value='szállításra vár'>szállításra vár</option>";
        echo "<option value='szállítás alatt'>szállítás alatt}</option>";
        echo "<option value='kiszállítva'>kiszállítva</option>";
    echo "</select>";
    echo "<br><br>";
    echo "<input type='hidden' name='hidden_id' value='{$row['id']}'>";
    echo "<input type='submit' value='Mentés' name = 'mentes'>";
    echo "</form>";
    
    